services:
  mongo_db:
    image: mongo:5.0.2
    container_name: mongodb
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - "27017:27017"
    volumes:
      - db:/data/db

  app:
    container_name: cryptora
    depends_on:
      - mongo_db
      - rabbitmq
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "8088:8088"
    environment:
      SPRING_APPLICATION_JSON: '{
          "spring.data.mongodb.uri" : "mongodb://root:123456@mongo_db:27017/binance?authSource=admin",
          "spring.rabbitmq.host" : "rabbitmq",
          "spring.rabbitmq.port" : 5672,
          "spring.rabbitmq.username" : "guest",
          "spring.rabbitmq.password" : "guest"
        }'
    volumes:
      - ~/.gradle:/home/gradle/.gradle
    stdin_open: true
    tty: true

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  db:
  rabbitmq_data: